/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./src/components/Editor/AreaSelect/index.tsx')['default']
    AuxiliaryLine: typeof import('./src/components/Editor/AuxiliaryLine/index.tsx')['default']
    BoundBox: typeof import('./src/components/Editor/BoundBox/index.tsx')['default']
    Chart: typeof import('./src/components/Chart/index.tsx')['default']
    ContextMenu: typeof import('./src/components/Editor/ContextMenu/index.tsx')['default']
    Editor: typeof import('./src/components/Editor/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./src/components/Editor/Scene/index.tsx')['default']
    SketchRuler: typeof import('./src/components/Editor/SketchRuler/index.tsx')['default']
    UseBoundbox: typeof import('./src/components/Editor/BoundBox/use-boundbox.ts')['default']
    UseCompose: typeof import('./src/components/Editor/hooks/use-compose.ts')['default']
    UseContextMenu: typeof import('./src/components/Editor/ContextMenu/use-context-menu.ts')['default']
    UseGroup: typeof import('./src/components/Editor/hooks/use-group.ts')['default']
    UseMouseEvent: typeof import('./src/components/Editor/hooks/use-mouse-event.ts')['default']
  }
}
