export {}

declare global {
  const Chart: typeof import('./../components/Chart/index.tsx')['default']
  const Editor: typeof import('./../components/Editor/index.tsx')['default']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NButton: typeof import('naive-ui')['NButton']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NCollapse: typeof import('naive-ui')['NCollapse']
  const NCollapseItem: typeof import('naive-ui')['NCollapseItem']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGi: typeof import('naive-ui')['NGi']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NColorPicker: typeof import('naive-ui')['NColorPicker']
  const NInput: typeof import('naive-ui')['NInput']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NRadioButton: typeof import('naive-ui')['NRadioButton']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NImage: typeof import('naive-ui')['NImage']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const NPopover: typeof import('naive-ui')['NPopover']
  const NTree: typeof import('naive-ui')['NTree']
  const NModal: typeof import('naive-ui')['NModal']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NRadio: typeof import('naive-ui')['NRadio']
  const NTab: typeof import('naive-ui')['NTab']
}
