// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AceEditor: typeof import('./components/Editor/AceEditor.vue')['default']
    Area: typeof import('./components/Editor/SelectedArea/Area.vue')['default']
    AreaSelect: typeof import('./components/Editor/AreaSelect/index.tsx')['default']
    AuxiliaryLine: typeof import('./components/Editor/AuxiliaryLine/index.tsx')['default']
    BoundBox: typeof import('./components/Editor/BoundBox/index.tsx')['default']
    Chart: typeof import('./components/Chart/index.tsx')['default']
    ComponentWrapper: typeof import('./components/Editor/ComponentWrapper.vue')['default']
    ContextMenu: typeof import('./components/Editor/ContextMenu/index.tsx')['default']
    Editor: typeof import('./components/Editor/index.tsx')['default']
    Grid: typeof import('./components/Editor/Grid/index.tsx')['default']
    MarkLine: typeof import('./components/Editor/MarkLine/index.tsx')['default']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    Preview: typeof import('./components/Editor/Preview.vue')['default']
    Primitives: typeof import('./components/Primitives/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ruler: typeof import('./components/Editor/Ruler/index.tsx')['default']
    SelectedArea: typeof import('./components/Editor/SelectedArea/index.tsx')['default']
    Shape: typeof import('./components/Editor/BoundBox/Shape.vue')['default']
  }
}
